export type PartnerTenant = {
  id: string;
  ownerEmail?: string;
  shopName: string;
  domainSlug: string;
  publicDomain: string;
  logoUrl?: string;
  promoImageUrl?: string;
  promoImageUrls?: string[];
  contactPhone?: string;
  promptPayId?: string;
  promptPayType?: "phone" | "national_id" | "tax_id" | "e_wallet" | string;
  bankName?: string;
  bankAccountName?: string;
  bankAccountNumber?: string;
  facebookPageUrl?: string;
  lineOaQrCodeUrl?: string;
  status: string;
  plan: string;
  createdAt?: string;
  updatedAt?: string;
};
