export type TenantProfile = {
  id: string;
  shopName: string;
  domainSlug: string;
  publicDomain: string;
  logoUrl?: string;
  promoImageUrl?: string;
  promoImageUrls?: string[];
  contactPhone?: string;
  promptPayId?: string;
  promptPayType?: "phone" | "national_id" | "tax_id" | "e_wallet" | string;
  bankName?: string;
  bankAccountName?: string;
  bankAccountNumber?: string;
  facebookPageUrl?: string;
  status?: string;
  bookingMode?: "payment" | "chat" | string;
  chatThresholdTHB?: number;
  plan?: string;
  createdAt?: string;
  updatedAt?: string;
};
