package routes

import (
	"github.com/gin-gonic/gin"
	"rentflow-api/controllers"
	"rentflow-api/middleware"
)

func RegisterRentFlowCarRoutes(r *gin.Engine) {
	r.Use(middleware.AttachRentFlowCarSession())

	r.POST("/auth/google", controllers.RentFlowCarAuthWithGoogle)
	r.POST("/auth/register", controllers.RentFlowCarRegister)
	r.POST("/auth/login", controllers.RentFlowCarLogin)
	r.POST("/auth/forgot-password", controllers.RentFlowCarForgotPassword)
	r.GET("/auth/me", controllers.RentFlowCarGetMe)
	r.POST("/auth/logout", controllers.RentFlowCarLogout)
	r.POST("/platform/auth/login", controllers.RentFlowCarAdminLogin)
	r.GET("/tenants", controllers.RentFlowCarListPublicTenants)
	r.GET("/tenants/resolve", controllers.RentFlowCarResolveTenant)
	r.GET("/users/:userId/avatar", controllers.RentFlowCarGetUserAvatar)
	r.GET("/tenants/:tenantSlug/logo", controllers.RentFlowCarGetTenantLogo)
	r.GET("/tenants/:tenantSlug/promo-image", controllers.RentFlowCarGetTenantPromoImage)
	r.GET("/tenants/:tenantSlug/promo-images/:imageId", controllers.RentFlowCarGetTenantPromoImageByID)
	r.GET("/tenants/:tenantSlug/storefront-images/:imageId", controllers.RentFlowCarGetStorefrontBlockImage)
	r.GET("/platform/settings/public", controllers.RentFlowCarGetPublicPlatformSettings)
	r.GET("/platform/settings/marketplace-promo-image", controllers.RentFlowCarGetMarketplacePromoImage)
	r.GET("/storefront/page", controllers.RentFlowCarGetStorefrontPage)
	r.GET("/ws/realtime", controllers.RentFlowCarRealtimeSocket)

	r.GET("/cars", controllers.RentFlowCarGetCars)
	r.GET("/cars/:carId/image", controllers.RentFlowCarGetCarPrimaryImage)
	r.GET("/cars/:carId/images/:imageId", controllers.RentFlowCarGetCarImage)
	r.GET("/branches", controllers.RentFlowCarGetBranches)
	r.GET("/branches/:branchId", controllers.RentFlowCarGetBranchByID)
	r.POST("/availability/check", controllers.RentFlowCarCheckAvailability)
	r.GET("/availability/:carId/unavailable-dates", controllers.RentFlowCarGetUnavailableDates)
	r.GET("/addons", controllers.RentFlowCarListAddons)

	r.POST("/bookings/preview", controllers.RentFlowCarPreviewBookingPrice)
	r.POST("/bookings", controllers.RentFlowCarCreateBooking)
	r.POST("/payments", controllers.RentFlowCarCreatePayment)
	r.GET("/payments/booking/:bookingId", controllers.RentFlowCarGetPaymentByBookingID)
	r.GET("/payment-slips/:paymentId", controllers.RentFlowCarGetPaymentSlip)
	r.GET("/reviews", controllers.RentFlowCarGetReviews)
	r.POST("/reviews", controllers.RentFlowCarCreateReview)
	r.POST("/ai/storefront-assistant", controllers.RentFlowCarStorefrontAssistant)

	protected := r.Group("/")
	protected.Use(middleware.RequireRentFlowCarSession())
	{
		protected.GET("/users/me", controllers.RentFlowCarUserMe)
		protected.PATCH("/users/me", controllers.RentFlowCarUpdateMe)
		protected.PATCH("/users/me/password", controllers.RentFlowCarChangePassword)

		protected.GET("/tenants/me", controllers.RentFlowCarGetMyTenant)
		protected.POST("/tenants/me", controllers.RentFlowCarUpsertMyTenant)
		protected.PUT("/tenants/me", controllers.RentFlowCarUpsertMyTenant)

		protected.GET("/partner/dashboard", controllers.RentFlowCarPartnerDashboard)
		protected.GET("/partner/ai/assistant", controllers.RentFlowCarPartnerAssistant)
		protected.GET("/partner/storefront/page", controllers.RentFlowCarPartnerGetStorefrontPage)
		protected.PUT("/partner/storefront/page", controllers.RentFlowCarPartnerUpdateStorefrontPage)
		protected.PATCH("/partner/storefront/page", controllers.RentFlowCarPartnerUpdateStorefrontPage)
		protected.POST("/partner/storefront/block-images", controllers.RentFlowCarPartnerUploadStorefrontBlockImage)
		protected.PATCH("/partner/storefront/promo-images/reorder", controllers.RentFlowCarPartnerReorderPromoImages)
		protected.DELETE("/partner/storefront/promo-images/:imageId", controllers.RentFlowCarPartnerDeletePromoImage)
		protected.GET("/partner/reports", controllers.RentFlowCarPartnerGetReports)
		protected.GET("/partner/reports/export", controllers.RentFlowCarPartnerExportReports)
		protected.GET("/partner/cars", controllers.RentFlowCarPartnerGetCars)
		protected.POST("/partner/cars", controllers.RentFlowCarPartnerCreateCar)
		protected.PATCH("/partner/cars/:carId", controllers.RentFlowCarPartnerUpdateCar)
		protected.DELETE("/partner/cars/:carId", controllers.RentFlowCarPartnerDeleteCar)
		protected.POST("/partner/cars/:carId/images", controllers.RentFlowCarUploadCarImages)
		protected.PATCH("/partner/cars/:carId/images/reorder", controllers.RentFlowCarPartnerReorderCarImages)
		protected.DELETE("/partner/cars/:carId/images/:imageId", controllers.RentFlowCarPartnerDeleteCarImage)
		protected.GET("/partner/branches", controllers.RentFlowCarPartnerGetBranches)
		protected.POST("/partner/branches", controllers.RentFlowCarPartnerCreateBranch)
		protected.PATCH("/partner/branches/:branchId", controllers.RentFlowCarPartnerUpdateBranch)
		protected.DELETE("/partner/branches/:branchId", controllers.RentFlowCarPartnerDeleteBranch)
		protected.GET("/partner/bookings", controllers.RentFlowCarPartnerGetBookings)
		protected.PATCH("/partner/bookings/:bookingId/status", controllers.RentFlowCarPartnerUpdateBookingStatus)
		protected.GET("/partner/bookings/:bookingId/operations", controllers.RentFlowCarPartnerGetBookingOperations)
		protected.POST("/partner/bookings/:bookingId/operations", controllers.RentFlowCarPartnerCreateBookingOperation)
		protected.GET("/partner/payments", controllers.RentFlowCarPartnerGetPayments)
		protected.PATCH("/partner/payments/:paymentId/verify", controllers.RentFlowCarPartnerVerifyPayment)
		protected.PATCH("/partner/payments/:paymentId/refund", controllers.RentFlowCarPartnerRefundPayment)
		protected.PATCH("/partner/payments/:paymentId/settle", controllers.RentFlowCarPartnerSettlePayment)
		protected.GET("/partner/customers", controllers.RentFlowCarPartnerGetCustomers)
		protected.GET("/partner/calendar", controllers.RentFlowCarPartnerGetCalendar)
		protected.POST("/partner/availability-blocks", controllers.RentFlowCarPartnerCreateAvailabilityBlock)
		protected.DELETE("/partner/availability-blocks/:blockId", controllers.RentFlowCarPartnerDeleteAvailabilityBlock)
		protected.GET("/partner/promotions", controllers.RentFlowCarPartnerListPromotions)
		protected.POST("/partner/promotions", controllers.RentFlowCarPartnerCreatePromotion)
		protected.PATCH("/partner/promotions/:promotionId", controllers.RentFlowCarPartnerUpdatePromotion)
		protected.DELETE("/partner/promotions/:promotionId", controllers.RentFlowCarPartnerDeletePromotion)
		protected.GET("/partner/addons", controllers.RentFlowCarPartnerListAddons)
		protected.POST("/partner/addons", controllers.RentFlowCarPartnerCreateAddon)
		protected.PATCH("/partner/addons/:addonId", controllers.RentFlowCarPartnerUpdateAddon)
		protected.DELETE("/partner/addons/:addonId", controllers.RentFlowCarPartnerDeleteAddon)
		protected.GET("/partner/leads", controllers.RentFlowCarPartnerListLeads)
		protected.POST("/partner/leads", controllers.RentFlowCarPartnerCreateLead)
		protected.PATCH("/partner/leads/:leadId", controllers.RentFlowCarPartnerUpdateLead)
		protected.DELETE("/partner/leads/:leadId", controllers.RentFlowCarPartnerDeleteLead)
		protected.GET("/partner/members", controllers.RentFlowCarPartnerListMembers)
		protected.POST("/partner/members", controllers.RentFlowCarPartnerCreateMember)
		protected.PATCH("/partner/members/:memberId", controllers.RentFlowCarPartnerUpdateMember)
		protected.DELETE("/partner/members/:memberId", controllers.RentFlowCarPartnerDeleteMember)
		protected.GET("/partner/domains", controllers.RentFlowCarPartnerListDomains)
		protected.POST("/partner/domains", controllers.RentFlowCarPartnerCreateDomain)
		protected.PATCH("/partner/domains/:domainId/verify", controllers.RentFlowCarPartnerVerifyDomain)
		protected.DELETE("/partner/domains/:domainId", controllers.RentFlowCarPartnerDeleteDomain)
		protected.GET("/partner/support", controllers.RentFlowCarPartnerGetSupport)
		protected.PATCH("/partner/support/tickets/:ticketId", controllers.RentFlowCarPartnerUpdateSupportTicket)
		protected.POST("/partner/support/tickets/:ticketId/messages", controllers.RentFlowCarPartnerCreateSupportMessage)
		protected.GET("/partner/audit-logs", controllers.RentFlowCarPartnerGetAuditLogs)
		protected.GET("/platform/me", controllers.RentFlowCarAdminGetMe)
		protected.GET("/platform/ai/assistant", controllers.RentFlowCarAdminAssistant)
		protected.GET("/platform/overview", controllers.RentFlowCarAdminGetOverview)
		protected.GET("/platform/partners", controllers.RentFlowCarAdminListPartners)
		protected.POST("/platform/partners", controllers.RentFlowCarAdminCreatePartner)
		protected.GET("/platform/domains", controllers.RentFlowCarAdminListDomains)
		protected.GET("/platform/billing", controllers.RentFlowCarAdminGetBilling)
		protected.PATCH("/platform/billing/invoices/:invoiceId", controllers.RentFlowCarAdminUpdateInvoiceStatus)
		protected.GET("/platform/security", controllers.RentFlowCarAdminGetSecurity)
		protected.PATCH("/platform/security/users/:userId", controllers.RentFlowCarAdminUpdateUserSecurity)
		protected.GET("/platform/security/members", controllers.RentFlowCarAdminListPlatformMembers)
		protected.POST("/platform/security/members", controllers.RentFlowCarAdminCreatePlatformMember)
		protected.PATCH("/platform/security/members/:memberId", controllers.RentFlowCarAdminUpdatePlatformMember)
		protected.DELETE("/platform/security/members/:memberId", controllers.RentFlowCarAdminDeletePlatformMember)
		protected.GET("/platform/audit-logs", controllers.RentFlowCarAdminGetAuditLogs)
		protected.GET("/platform/settings", controllers.RentFlowCarAdminGetPlatformSettings)
		protected.PUT("/platform/settings", controllers.RentFlowCarAdminUpdatePlatformSettings)
		protected.PATCH("/platform/settings", controllers.RentFlowCarAdminUpdatePlatformSettings)
		protected.GET("/platform/storefront/page", controllers.RentFlowCarAdminGetStorefrontPage)
		protected.PUT("/platform/storefront/page", controllers.RentFlowCarAdminUpdateStorefrontPage)
		protected.PATCH("/platform/storefront/page", controllers.RentFlowCarAdminUpdateStorefrontPage)
		protected.GET("/platform/tenants", controllers.RentFlowCarAdminListTenants)
		protected.PATCH("/platform/tenants/:tenantId/status", controllers.RentFlowCarAdminUpdateTenantStatus)

		protected.GET("/bookings/me", controllers.RentFlowCarGetMyBookings)
		protected.GET("/bookings/:bookingId", controllers.RentFlowCarGetBookingByID)
		protected.PATCH("/bookings/:bookingId/cancel", controllers.RentFlowCarCancelBooking)

		protected.POST("/cars/:carId/images", controllers.RentFlowCarUploadCarImages)

		protected.GET("/notifications", controllers.RentFlowCarGetNotifications)
		protected.PATCH("/notifications/:notificationId/read", controllers.RentFlowCarMarkNotificationAsRead)
		protected.PATCH("/notifications/read-all", controllers.RentFlowCarMarkAllNotificationsAsRead)
	}
}
